# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-29 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='away_team_goals',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='event',
            name='home_team_goals',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
